### PR TITLE
Add fileIncludePath option

### PR DESCRIPTION
**Pull request by jklukas**
Addresses #19

### CODE REVIEW

**Comment by jklukas** [comment]
@tkrille - I just updated this PR with documentation of the new interface for includes.

**Comment by tkrille** [comment]
Wow, thanks again for your awesome work @jklukas!

**Comment by tkrille** [comment]
When do you need a release for this?

**Comment by jklukas** [comment]
I don't have any immediate plans for using this in a project, so no hard deadline. It would be great to see this out in the next week or two.

**Comment by tkrille** [comment]
Alright, I'll prepare everything.

**Comment by tkrille** [comment]
Done: https://github.com/tkrille/dropwizard-template-config/releases/tag/v1.4.0

**Pull request merged**
